### ISSUE TITLE
Relayer behind metric should not be firing when messages are going to non-configured domains

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1688]
We have a `mainnet2 relayer message leaf index is behind validator signed leaf index` alert which indicates when the relayer might be behind on the `processor_loop` despite us knowing a higher index from the validators. This alert triggers right now when the messages at the tip are to domains which the relayer is not configured for

https://discord.com/channels/935678348330434570/935679524534911007/1068641165391450263

**Comment by mattiecnvr** [comment]
After review, I think the issue is not when the message is sent to an unknown chain but rather that it was alerting when we re-deployed and the processor loop had to catch up. My solution for now is going to be to increase the evaluation time to 10m from 2m which will still be fairly responsive but less prone to alerting during relayer init.
