### ISSUE TITLE
Investigate frequent "Unable to fetch metadata for message" logs in relayer

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1777]
In my latest deploy, I was poking through logs and noticed that the relayers can often get in situations where they've indexed a message & corresponding gas payment, but they're unable to fetch metadata, as shown by a generic `"Unable to fetch metadata for message"` log. This seems to happen multiple times when retrying a message and sometimes causes messages to be relayed minutes later than I'd expect them to

Are many validators behind? Or is something else up? Example (this is for the message from Ethereum with nonce 369 - this example doesn't show a super long time before the msg is eventually relayed, but it does show many "Unable to fetch metadata for message" logs: https://cloudlogging.app.goo.gl/FTv7LkT1t5qoFmU6A

**Comment by tkporter** [comment]
Here's a better example with a more explicit filter on the message with nonce 368 https://cloudlogging.app.goo.gl/18EEKaSwHMrB7ck5A

Ends up being processed like 5 mins later than when it's first indexed

@asaj has a good point that maybe we are indexing messages with a smaller lag than validators are using when signing

**Comment by nambrot** [comment]
Whatever the cause, the logs should be more help to indicate to the operator why metadata cannot be fetched

**Comment by mattiecnvr** [comment]
This is probably because `fetch_metadata` in `relayer/src/metadata_builder.rs` is returning `Ok(None)` and for some reason that means the serial submitter just logs that info and then does not relay the message.

So that makes me wonder if there is actually anything an operator can do? The only other place the message could come from is in the `sponsored_call_op.rs` file for the `GelatoSubmitter` and that is basically caused by the same thing.

**Comment by nambrot** [comment]
If there is nothing an operator can we then we should consider reducing the verbosity, but IMO it can be incredibly helpful to the operator to know why metadata was not able to be fetched.

**Comment by mattiecnvr** [comment]
I will see what I can do to give more context.
