### ISSUE TITLE
Agent errors when trying to unwrap none config value with cryptic error

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#2105]
https://discord.com/channels/935678348330434570/1096444620172431410/1096789219189465088

**Comment by nambrot** [comment]
Yeah IIRC i also ran into this and was here https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/91837d8a2083392e6d1349c6ad020f761264e4de/rust/hyperlane-base/src/settings/chains.rs#L273

I don't recall what the fix was though. The error handling looks solid though, @mattiecnvr can you see why we would be unwrapping domain (or something else here?)

**Comment by mattiecnvr** [comment]
Ah, yeah I see the problem. It uses `and_then` without raising an error if it had been none before trying to parse. So if it wasn't set there's just no error and it ends up in the unwrap case. Trivial to fix.
