### ISSUE TITLE
Agent docs/config improvements after EthTokyo

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2113]
Problems:
            - A lot of configuration fatigue
            - missing field `validator` is too vague
            - No such file or directory (os error 2) is a frustrating error
            - Machine specs section on starting a validator looks out of place
            - `Error: Destination chain base does not have a configured signer` feels not as actionable as we can be
            - `Missing chain configuration for sepolia; this includes protocol type and the connection information` is quite vague
            - in the relayer guide, similar to the validator guide, the specific sequence is a bit unclear. Going page by page gets me to message filtering which i should not need to check out. The Env page does again not distinguish between required and optional vars and does not tell me what the next step is, when i am done
            - Way too easy to miss `HYP_RELAYER_ALLOWLOCALCHECKPOINTSYNCERS`
            - Not mounting the DB_PATH will result in relayers needing to index from genesis every time which is very annoying
            - When running two relayers locally, it is possible to actually have both read/write to the same DB which is very hard to debug and obviously does not work
            -  "no name found" - typo results in weird message
            - When restarting anvil, previous artifacts are no longer valid, but very hard to debug

Possible Solutions (not exhaustive):
            - Collapse running validator/relayer into a single page as much as possible
            - Default validator interval to something like 5s
            - Default HYP_BASE_METRICS (maybe already done)
            - Default HYP_BASE_TRACING_LEVEL and FORMAT (maybe already done)
            - Segment the environment variables/config into required and optional ones (i.e. ones that have reasonable defaults should be further down)
            - “missing field `validator`” should have a more useful message indicate to specify the validator key
            - When using localStorage checkpoint synced, just create the directory if it doesn’t exist
            - When signers are missing, point to default signer as much as possible
            - If an RPC url is missing, call it out as such, don’t say chain configuration is missing with protocol type and connection information
            - HYP_RELAYER_ALLOWLOCALCHECKPOINTSYNCERS needs to be made more obvious. When it’s not enabled but we discover a local storage checkpoint synced, we should log an info log line to indicate that this is the issue why metadata could not be fetched
            - Indicate that relayers when using docker should mount external storage for DB_PATH
            - Detect when the agent runs on a DB for which it was not configured (i.e. its the DB of some other agents)
            - "no name found" - should have a more clear error message that they probably have a typo in the RPC url env var

**Comment by mattiecnvr** [comment]
Current default if the metrics port is not defined is to just not host the metrics webserver at all which we _could_ change but then there might be conflicts if they try to run multiple agents at once. I think this also fine because I would assume metrics are more of an "Advanced configuration" piece that is not really relevant for getting something up and running at first.

I am also generally cutting down the configuration that is "required" since we now have the reference page for anyone who wants get more into the weeds.

tracing config (level and fmt) already default so removing them from the guide (still in the reference).

Not sure where "Missing field `validator`" came from, I think that is an old message now.

With the most recent release, the default database directory now includes the chain name, so hopefully that will prevent the conflicts between relayers. Adding docs though to help clarify for people that specify it manually.

**Comment by mattiecnvr** [comment]
TODO: update metric port to default to 9090 and log a warning if we cannot start the metrics server due to a conflict.

**Comment by mattiecnvr** [comment]
Not sure where "no name found" comes from; any additional context?

> When restarting anvil, previous artifacts are no longer valid, but very hard to debug
What is the desired change for this? I can add a message somewhere but not sure how to detect this case.

**Comment by nambrot** [comment]
> Not sure where "Missing field `validator`" came from, I think that is an old message now.

I believe this happens when you don't specify the validator signer? Or what is the error message now?

> 
> With the most recent release, the default database directory now includes the chain name, so hopefully that will prevent the conflicts between relayers. Adding docs though to help clarify for people that specify it manually.

Oh I like that

**Comment by nambrot** [comment]
> Not sure where "no name found" comes from; any additional context?

If you specify a connection URL with a typo in the chain name, imo that is the error message that (used to) pop up (which indeed is hard to tell where it comes from :))

> 
> > When restarting anvil, previous artifacts are no longer valid, but very hard to debug
> What is the desired change for this? I can add a message somewhere but not sure how to detect this case.

You can make an `eth_getCode` call at the contract addresses, and if it doesnt return anything it means the contract does not exist, and I would probably log it as an error. You can just do this maybe when the call to the mailbox root reverts

**Comment by mattiecnvr** [comment]
Went ahead and made it so the database officially works with multiple domains (technically it already did but it was poorly documented and was implemented as a hack (before my time)). I figure this will also help with #1899

**Comment by mattiecnvr** [comment]
> > Not sure where "Missing field validator" came from, I think that is an old message now.
>
> I believe this happens when you don't specify the validator signer? Or what is the error message now?


It should now just default to `SignerConf::Node`

> > Not sure where "no name found" comes from; any additional context?
>
> If you specify a connection URL with a typo in the chain name, imo that is the error message that (used to) pop up (which indeed is hard to tell where it comes from :))

Not going to worry about this for the moment with #1867 changing how that works anyway. Not honestly sure what I can do anyway since if they put in the wrong chain name it will have the wrong path. I can't fix that but it should at least list the path it tried to follow.


> > > When restarting anvil, previous artifacts are no longer valid, but very hard to debug
What is the desired change for this? I can add a message somewhere but not sure how to detect this case.
> 
> You can make an `eth_getCode` call at the contract addresses, and if it doesnt return anything it means the contract does not exist, and I would probably log it as an error. You can just do this maybe when the call to the mailbox root reverts

I do not see a good place to change this in the code. The mailbox is constructed without checking the address it looks like and then there's just a bunch of different calls it supports. And at any of the points the error could be something other than an invalid mailbox.
