### ISSUE TITLE
Sealevel Mailbox - mark messages as delivered using PDAs

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2208]
At the moment, there is a `delivered: HashSet<H256>` in the Inbox account, which is used for replay protection to ensure that messages that have already been processed can't be processed. The ID of a message (which is the keccak hash of the entire message, including origin/sender/recipient/destination/nonce/body, etc) is inserted into the hashset when it's been processed in a `inbox_process`. If the message has already been processed, the transaction should error.

We want this exact same behavior preserved, but the current approach of using a HashSet in the inbox account isn't scalable - the max size of the inbox account is 10 MiB (because it's a PDA-based account). So instead of using a HashSet in the inbox account, we should instead use PDAs. We can have the PDA seed be based on the message's ID, something like `message-delivered-${message.id()}`. If an account at that PDA exists already, `inbox_process` should revert. If it doesn't exist already, then the message should be processed and then the rent-exempt account at that PDA should be created.

Note this means that the PDA with the seed `message-delivered-${message.id()}` will need to be passed in as an account on the client side when `process` transactions are created.

So concretely:
1. Remove the `delivered: HashSet<H256>`
2. Move to using PDAs for replay protection
3. Update client side / agent code / test code as necessary to ensure everything still works end to end

**Comment by Hyperlane-Cryptolutions** [comment]
Here are the steps to implement replay protection using PDAs in the Sealevel Mailbox:

Remove the delivered: HashSet<H256> from the Inbox account.
Add a new function to the Inbox account called inbox_process_with_pda. This function should take an additional parameter, which is the PDA that will be used to store the replay protection flag.
In the inbox_process_with_pda function, first check if the PDA already exists. If it does, then the message has already been processed and the transaction should revert. If the PDA doesn't exist, then the message should be processed and the rent-exempt account at that PDA should be created.
Update the client side code to pass in the PDA with the seed message-delivered-${message.id()} when creating process transactions.
Update the agent code to call inbox_process_with_pda instead of inbox_process when processing messages.


`pub fn inbox_process_with_pda(
    &mut self,
    message: &Message,
    pda: &mut Account,
) -> Result<(), Error> {
    // Check if the PDA already exists.
    if pda.exists() {
        return Err(Error::AlreadyProcessed(message.id()));
    }

    // Process the message.
    self.process_message(message)?;

    // Create the rent-exempt account at the PDA.
    pda.create_rent_exempt()?;

    Ok(())
}
`

**Comment by tkporter** [comment]
done with #2300
