### ISSUE TITLE
Optimize validator latest checkpoint polling

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#2272]
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2246 made indexing more efficient.
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2187 introduces message indexing to validators. We are still polling for the latest checkpoint with a view call every `interval` seconds in the validator even though we could rely exclusively on indexing via DB polling or a message [channel](https://tokio.rs/tokio/tutorial/channels).

**Comment by asaj** [comment]
I think we would still want the forward-checkpoint-submitter to check correctness via `latestCheckpoint`, for now at least. But this could be made more efficient, where we call latest_checkpoint iff `target_checkpoint.is_none() && !queue.is_empty()` (I think)

The legacy checkpoint submitter could rely entirely on an incremental tree populated via the DB, because we don't expect to have slashing for legacy checkpoints.

**Comment by tkporter** [comment]
@yorhodes given we've soured on validator indexing, cool to close this?

**Comment by nambrot** [comment]
Agreed, closing
