### ISSUE TITLE
HyperlaneRocksDB store_logs debug logs do not show in E2E test

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#2282]

**Comment by asaj** [comment]
@mattiecnvr, any idea why this is happening?

**Comment by mattiecnvr** [comment]
I have 2 ideas.

1) check in the e2e test if we are capturing the stdout for the process that you are interested in or if it is just going into the log file. I think some of them we don't send to the console but only to log files unless you enable LOG_ALL or something like that.
2) we filter some logs out to only show at trace (regardless of what level they say they are); this change was made because we did not hvae conrol over all the subsystem's definitions of log levels and found them to be very verbose

**Comment by mattiecnvr** [comment]
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/rust/hyperlane-base/src/settings/trace/mod.rs#L75

Is one of the relevant areas. I don't think that will filter your store_logs outputs. So it is probably (1).
