### ISSUE TITLE
Investigate ethers-rs middleware for "stuck" txs

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2959]
### Context
The relayer submits a transaction with a gas price that is no longer high enough to execute, but instead of the relayer submitting on certain networks like polygon the tx is stuck in the mempool. To "unstuck" the relayer needs to submit a higher bid with x% more gas, but our relayer currently lacks that logic.

https://docs.rs/ethers/latest/ethers/middleware/struct.GasEscalatorMiddleware.html is probably what we want

Some things to note:
- See https://cloudlogging.app.goo.gl/jXpgMgTHsWZpUk1s9 for examples of this. Interestingly, this only seems to happen with polygon txs and still occurs pretty frequently.
- This was originally written with Polygon in mind that we fixed in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2965. Addressing https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2924 is now the main focus of this. Seemingly the Polygon fix wasn't totally sufficient 
- Be careful of our usage around fallback provider here (e.g. if the gas escalation only works at the "inner provider" level and not at a higher level, this may not actually be useful)
- Be careful that we construct new providers pretty frequently, e.g. when constructing metadata. I believe we use the same provider for all tx submission, but maybe we don't. I believe we'd need to use the same long-living provider if we wanted to use the gas escalator middleware

**Comment by yorhodes** [comment]
https://docs.rs/ethers/latest/ethers/middleware/struct.GasEscalatorMiddleware.html

**Comment by tkporter** [comment]
nice, we'll have to make sure the footgun / issues aren't a problem for us & also that this covers the case of immediately getting back a "transaction underpriced" error and not just if the tx doesn't get included in a block in time

**Comment by daniel-savu** [comment]
> Be careful of our usage around fallback provider here (e.g. if the gas escalation only works at the "inner provider" level and not at a higher level, this may not actually be useful)

Afaict ([source code](https://docs.rs/ethers-middleware/2.0.14/src/ethers_middleware/gas_escalator/mod.rs.html#158-163)) the logic is compatible with our fallback provider middleware - we just need to make sure that "Gas Escalator" is the outermost middleware.



> Be careful that we construct new providers pretty frequently, e.g. when constructing metadata. I believe we use the same provider for all tx submission, but maybe we don't. I believe we'd need to use the same long-living provider if we wanted to use the gas escalator middleware

Had a look, indeed we only transact via long-lived instances (`mailbox` and `validator_announce`), although we have no safety mechanisms in place to protect against future mis-uses.



>  the case of immediately getting back a "transaction underpriced" error and not just if the tx doesn't get included in a block in time

If we get back an error, it just gets propagated. I believe this is less of an issue since the message will be retried if submission fails, but we could include this specific error message in the retrying provider logic [here](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/0cf692e7315cb91059a4c0b39c7cdf76151851cc/rust/chains/hyperlane-ethereum/src/rpc_clients/mod.rs#L38).

**Comment by tkporter** [comment]
> We're not susceptible to the "memory leak" bug as long as we have one RPC still live - because as soon as one of them comes back online, resubmits start happening.

I think it's still possible to get an error from a provider even if they're technically "live", (e.g. if we're low on funds or the gas price is too low or something and can't successfully submit a transaction) and the task will error here https://github.com/hyperlane-xyz/ethers-rs/blob/hyperlane/ethers-middleware/src/gas_escalator/mod.rs#L223

But in any case I'm comfortable treating this as an unlikely edge case that we're aware of and we can revisit if we have issues
