### ISSUE TITLE
Scraper cosmos support: fully implement `HyperlaneProvider` for `CosmosProvider`

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3332]
## Problem

The scraper requires the `HyperlaneProvider` trait to be fully implemented for a particular chain. We previously put some `todo!()`s here or placeholder return values

## Solution

- I believe `get_block_by_hash` and `get_txn_by_hash` are the only strictly required ones, but while we're at it it'd be nice to fully implement all the fns.
- Imo `cumulative_gas_used` is useless in `TxnReceiptInfo` and we can probably remove: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/e737d998ff23b5aa6cf2be9634789ca5dc5a4275/rust/hyperlane-core/src/types/chain_data.rs#L60. I'll defer if this seems more hassle than it's worth to change the db schema for this, but fwiw we'll be making a bunch of db changes anyways
- Imo the best testing of this will be in https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3355 -- if we want to  get some confidence though we can consider some "integration" style tokio::tests to just try it against a live URL (no need to check this in imo though)

**Comment by DiForss** [comment]
It sounds like you have a clear understanding of what needs to be done to implement the HyperlaneProvider trait for a particular chain in the scraper. Since get_block_by_hash and get_txn_by_hash are the only strictly required functions, focusing on implementing those first is a good approach. However, taking the opportunity to fully implement all the functions would be beneficial.

Regarding the cumulative_gas_used field in TxnReceiptInfo, if you believe it's unnecessary, removing it from the scraper schema might be a good idea. However, if removing it causes complications, it might be best to leave it for now and revisit it later.

Testing the implementation, especially against live URLs, is crucial for ensuring its functionality. While integration-style tests using tokio::tests may provide confidence, they might not need to be checked in as long as they're used for testing purposes.

It seems like you've got a solid plan in place. If you encounter any challenges or need further assistance with the implementation or testing, feel free to ask!
