### ISSUE TITLE
CLI artifact fields should be ordered alphabetically

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#4057]
See request [here](https://github.com/hyperlane-xyz/hyperlane-registry/pull/73?notification_referrer_id=NT_kwDOAArYX7IxMTIyNzg2NjYwMzo3MTA3NTE#issuecomment-2189170498)

And some more context [here](https://github.com/hyperlane-xyz/hyperlane-registry/pull/39)

**Comment by bertux** [comment]
To discover more deeply how the CLI works I would be interested to try to find a solution for this request I made.

**Comment by avious00** [comment]
hey @bertux we're happy to support you as you try this contribution

I also added a $250 bounty if you solve it :)

**Comment by jmrossy** [comment]
@bertux It may be sufficient to improve this yaml util function in the CLI but I'm not 100% sure. 
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/cli/src/utils/files.ts#L93

**Comment by bertux** [comment]
thanks @jmrossy for the precise line which writes the YAML file, I will look what is available in this yaml library to write it sorted alphabetically instead of linearly. I could also try to sort before writing as I've done manually but it may be less readable so I will let you know what I will find.

**Comment by bertux** [comment]
Thank you, I agree it looks very promising, I will test that as soon as I get some time this week and then propose a PR using it.
It should be simple for this good first issue.
