### ISSUE TITLE
Upon startup, validators should write some metadata about themselves to their checkpoint syncer

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#4226]
## Problem

A few times we've wanted to easily see what version a validator operator is running without asking them. This helps understand if validators are running old versions that are prone to bugs that have since been fixed, and also helps us debug problems they may be seeing.

## Solution

Similar to how a validator will put an announcement.json in their checkpoint syncer (example https://hyperlane-mainnet3-arbitrum-validator-0.s3.us-east-1.amazonaws.com/announcement.json), we can have validators write another file (e.g. imagine metadata.json, but there's probably a better name than that) that includes the validator version they're operating.

I imagine the git commit is the easiest thing here to support both Docker images and those built from source. It should be updated upon validator startup.

## Nice to Have

Might be nice to think about other info we could put in here. We have the validator address + storage location in the announcement.json.

Maybe the current time at startup? Could help us debug things we've seen, like a validator skipping some messages and us speculating this is because they had brief downtime and then struggled to backfill

**Comment by tkporter** [comment]
Success criteria:
- check existence of this file in e2e
- or just roll out and visually see

**Comment by ameten** [comment]
## Solution options

### Option A
Write information about validator to a single file (`metadata.json` file) when the validator starts up

Pros
* Simple implementation
* No redundant information about validator

Cons
* Only the latest information is available
* Information about the validator historical startups is not available

### Option B
Write information about validator into checkpoint file

Pros
* Information about validator is available in every checkpoint file
* Information about validator is available to relayer
* Keep history of validator versions

Cons
* We need to be careful about adding new fields to checkpoint file keeping it backward compatible since relayer should be able to read it
* Same information will be written to many checkpoint files making it redundant

### Option C
Write separate file when validator starts.

Option C1 - `metadata_timestamp.json` - timestamp provides the time when validator started.
Option C2 - `metadata_next_checkpoint_index.json` - next checkpoint index provide the starting checkpoint provided by the validator.

Pros
* Single file on every validator restart
* Keep history of validator versions

Cons
* If validator restarts frequently, any files will be produced

**Comment by tkporter** [comment]
Good ideas and I love the presenting of the options with pros/cons!

For option B, agree with your callout that adding a new field would need to be backward compatible - do you know if it is? If it's not then agree this isn't possible

I like option C's preserving of the validator version history. So I understand correctly, with option C1 we'd expect of objects like `metadata_1723019315.json` or something? I think we'd want an easy way for us to quickly get the latest metadata, curious if you know of an easy way to do this. Maybe sorting objects via the AWS API or maybe a `metadata_latest.json` or something

**Comment by ameten** [comment]
For Option B, we can make the field optional (`Option<>`) or provide a default value. In this case all combinations of new and old version of validators and relayers will be able to work with each other.

Option C2 won't work (`metadata_next_checkpoint_index.json`):
* Validator process messages in reverse order. It means that it can process transaction with nonce (checkpoint index) 10, crash, new instance can start and process transaction with nonce 9. If the new instance of validator uses newer binary, having next checkpoint index in the name of the file does not help to identify which version of the validator produce particular checkpoint file.

**Comment by ameten** [comment]
### Elaborated Solution 

Store the history of validator versions. This solution allows to link each checkpoints to the version of validator which produced them.

* Add timestamp into validator checkpoint files
* Create new file every time validator starts (`metadata_<timestamp>.json`)

### Pragmatic Solution

Store only the version of validator which is running or was the last running.

* Overwrite file every time validator starts (`metadata_latest.json`)

### Decision

We shall implement Pragmatic Solution as it covers 95% of our needs and we shall leave the Elaborated Solution for future development.

**Comment by tkporter** [comment]
done by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4282, thanks @ameten
