### ISSUE TITLE
Anyone should be able to assess whether prospective validators operate as expected

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#661]
Validators can run in a permissionless manner without any networking or consensus. To be considered for addition to the Abacus validator set, any party should be able to compare their performance to other validators. It likely makes sense to just create a script in infra that uses the existing `ChainValidatorSets` config to fetch signatures, their metadata (like timestamps) and see that they seem to be operating correclty.

**Comment by tkporter** [comment]
The behavior of a "correctly" operating validator is:
* Whenever a block `checkpoint_block` on the Outbox chain contains 1 or more dispatched messages, the checkpoint with the index of the last message dispatched in that block should be signed by the validator upon observing block `checkpoint_block + reorg_period`

How we should test this:

* An infra script is passed:
   * the address of the validator
   * the S3 bucket of the validator
   * the environment
   * the chain name
   * an optional RPC url for the chain. If not provided, the default one from the multiprovider should be used. Allowing this to be overridden is nice for 3rd party people who may want to run the script without needing access to our GCP secrets where our RPC urls are
* The script should look for each Outbox `Dispatch` event backward from the current Outbox block number (consider also making this something that can be passed into the script, if that seems useful) all the way till the message with index 0 (or possibly a configurable block number or message index, if that seems useful).
* If there are multiple `Dispatch` events in a single block `B`, the one with the highest index `message_index` is picked. The script should then find the block number at which block `B` is finalized, which is `B_final = B + # of blocks till finality`. The script should then look up the timestamp of `B_final` using an `eth_getBlock` call, `B_final_timestamp`. This is about the lowest timestamp that we'd expect the validator to sign the checkpoint with index `message_index`. The script should then:
   * Get the validator's signature from S3. The script should ensure that it's a legitimate signature by the validator's address over the expected checkpoint. Getting the correct root for the checkpoint may actually be pretty annoying. It's really easy if the RPC provider is an archive node that allows state reads from a very long time ago, but I'm not so sure we should assume that someone running this script has access to an archive node. One idea is to be able to pass into the script a "model" validator's S3 bucket that is already known to have correct checkpoint roots, and this is where checkpoint roots are fetched from. The script could also read them from archive nodes if configured to do so (i.e. allowing the "model" validator to be proved as correct by us before telling 3rd party validators to compare themselves against the model).
   * The script should then get the `LastModified` timestamp of the validator's checkpoint signature S3 object metadata. The script should ensure that the timestamp is `>=` the `B_final_timestamp`, ensuring that the validator is waiting at least the recommended reorg period.

Note that these are all valid situations:
* The validator has not been operating since the core contracts were first deployed, so it hasn't signed older checkpoints
* The validator maybe had some downtime before
* The timestamp of the first checkpoint a validator signs upon starting up is >> `B_final_timestamp`

I think it'd be nice to just have the script output some relevant information that we as humans can decipher to determine if it's behaving as we'd expect or not, rather than the script completely making that decision itself. Some relevant things I can think of are:
* How many seconds after `B_final_timestamp` the validator's `LastModified` timestamp is. We could display this for each signed checkpoint, or maybe using a histogram or something (histogram may be confusing in bits where the validator signs a checkpoint upon first starting up, causing the `LastModified` timestamp - `B_final_timestamp` to be really large). Anything negative here is probably concerning
* Any checkpoints that weren't signed that we'd expect them to. This may happen if the validator's polling interval is too low, or maybe they weren't operational at the time
* If _any_ checkpoints are signed by a different address than we expected

Some good test cases:
* One of our own validators, e.g. the Celo one `https://abacus-mainnet-celo-validator-0.s3.us-east-1.amazonaws.com/` whose address is `0x8784f09c2cfb70329b936a3b75eb61c41b467b65`
* The ZKV Celo validator `https://abacus-mainnet-zkv-celo-signatures.s3.eu-west-2.amazonaws.com/` (should find out what their address is)
* One of our polygon validators, e.g. `https://abacus-mainnet-polygon-validator-0.s3.us-east-1.amazonaws.com/` whose address is `0xff198cae21069d865b142f2b9e798d3b299b8df6`. This one is quite interesting because we initially set the # of blocks till finality to 500, whereas now we've set it to something lower (256). So some of the checkpoints will be signed much later than we'd expect, but the more recent ones should be signed about as we'd expect.
* The ZKV Polygon validator `https://abacus-mainnet-zkv-polygon-signatures.s3.eu-west-2.amazonaws.com/` (should find out what their address is)

**Comment by nambrot** [comment]
This is very elaborate, thanks @tkporter 

I was personally thinking of a smaller scope to start with. Basically comparing two validators and mostly assuming that 1 is operating already as expected should make some of the search for dispatches and checkpoints superflous. I.e. could you just look for the checkpoints of an Abacus Works validators and compare their existence/timestamps to the ZKV one.

**Comment by tkporter** [comment]
@nambrot We've changed the finality numbers a few times so historically a bunch of the checkpoints signed by our validators are not really done as we would now expect them to. I think it may also be nice to have a more advanced script because there are other factors at play like the polling interval that we haven't put a ton of thought into for the validators that we operate. Personally I think it's worth a bit more effort to have some more confidence about the expected behavior of a validator (including our own) but if you feel that our time is better spent elsewhere, I'm happy to cut scope

**Comment by tkporter** [comment]
@mattiecnvr I just updated the scope in the comment, lmk if you have questions on it so far.

@nambrot if you want, feel free to check out the scope and see if there's anything worth adding/removing

**Comment by nambrot** [comment]
Slight modifications I would make:
- When itereating through the checkpoint indexing starting from the highest. After like 10 missing indicies of the prospective validator, I would just exit the loop as an indication that that's when we assume the validator started validating.
